package main

const (
	AddUser = `
		INSERT INTO TB_USER (USER_ID, USER_NAME, USER_EMAIL, USER_PASSWORD,
							 USER_PHONE, USER_BIRTH, USER_TYPE)
		VALUES(default, $1, $2, $3, $4, $5, 2);
	`
	AddAdmin = `
		INSERT INTO TB_USER (USER_ID, USER_NAME, USER_EMAIL, USER_PASSWORD,
			USER_PHONE, USER_BIRTH, USER_TYPE)
		VALUES(default, $1, $2, $3, $4, $5, 1);
	`

	RemoveUser = `
		DELETE FROM TB_USER WHERE USER_ID = $1;
	`
	UpdateUser = `
		UPDATE TB_USER SET 
			USER_NAME = $1,
			USER_MAIL = $2,
			USER_PASSWORD = $3,
			USER_PHONE = $4,
			USER_BIRTH = $5
		WHERE USER_ID = $6;
	`
	SelectUser = `
		SELECT USER_ID, USER_NAME, USER_EMAIL, USER_PHONE, USER_BIRTH, USER_TYPE
		FROM TB_USER WHERE USER_ID = $1;
	`

	FetchUsers = `
		SELECT USER_ID, USER_NAME, USER_EMAIL, USER_PHONE, USER_BIRTH, USER_TYPE
		FROM TB_USER;
	`

	AddObject = `
		INSERT INTO TB_OBJECT VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9);
	`
	UpdateObject = `
		UPDATE TB_OBJECT SET 
			OBJECT_NAME = $1, 
			OBJECT_STATUS = $2, 
			OBJECT_TYPE = $3
		WHERE OBJECT_ID = $4;
	`
	RemoveObject = `
		DELETE FROM TB_OBJECT WHERE OBJECT_ID = $1;
	`
	SelectObject = `
		SELECT * FROM TB_OBJECT WHERE OBJECT_ID = $1;
	`

	FetchObjects = `
			SELECT * FROM TB_OBJECT;
	`

	SetStateObject = `
		UPDATE TB_OBJECT SET OBJECT_STATUS = $1
		WHERE OBJECT_ID = $2;
	`

	SetAttrLight = `
		UPDATE TB_OBJECT SET OBJECT_ATTR_INTENSITY = $1
		WHERE OBJECT_ID = $2;
	`
	SetAttrSound = `
		UPDATE TB_OBJECT SET OBJECT_ATTR_VOLUME = $1
		WHERE OBJECT_ID = $2;
	`
	SetAttrSensor = `
		UPDATE TB_OBJECT SET OBJECT_ATTR_DISTANCE = $1
		WHERE OBJECT_ID = $2;
	`
	SetAttrAirConditioner = `
		UPDATE TB_OBJECT SET OBJECT_ATTR_TEMPERATURE = $1 
		WHERE OBJECT_ID = $2;
	`

	Login = `
		SELECT * FROM TB_USER 
		WHERE USER_EMAIL = $1 AND USER_PASSWORD = $2;
	`

	InviteNew = `
		INSERT INTO TB_INVITE (INVITE_ID, INVITE_SENDER, INVITE_RECEIVER) 
		VALUES(default, $1, $2);
	`
	InviteDelete = `
		DELETE FROM TB_INVITE WHERE INVITE_ID = $1;
	`
	InviteFetch = `
		SELECT * FROM TB_INVITE WHERE INVITE_RECEIVER = $1;
	`
)
